name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/yeogigangwon-frontend:latest .

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/yeogigangwon-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/yeogigangwon-frontend:latest
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker run -d --name frontend-app -p 80:80 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/yeogigangwon-frontend:latest
